[package]
name = "adder"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { version = "0.21.0", default-features = false, features = ["realloc"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "docs:calculator"

[package.metadata.component.target]
path = "../wit/calculator.wit"
world = "adder"

[package.metadata.component.dependencies]
